language: python
python:
  - '3.6'

# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - ansible-lint install macbook/*.yml -x 303,701,601,206,602,403,301,502,306,208,220 -v 
  - ansible-lint install linux/*.yml -x 303,701,601,206,602,403,301,502,306,208,220 -v 
 
