dist: bionic
language: python
python:
  - '3.6'
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - ansible-lint install macbook/mac-catalina.yml -x 303,701,601,206,602,403,301,502,306,208,220,201 -v
  - ansible-lint install linux/ubuntu.yml -x 303,701,601,206,602,403,301,502,306,208,220,201 -v
  - ansible-lint install vps/vps.yml -x 303,701,601,206,602,403,301,502,306,208,220,201 -v