trigger:
- main
pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    Python37:
      python.version: '3.7'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'

- bash: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  
- bash: | 
    ansible-lint linux/ubuntu.yml -x 303,701,601,206,602,403,301,502,306,208 -v
    displayName: 'Run Linter on Ubuntu'

- bash: | 
    ansible-lint vps/vps.yml -x 303,701,601,206,602,403,301,502,306,208 -v
    displayName: 'Run Linter on VPS'

- bash: | 
    ansible-lint macbook/macbook-catalina.yml -x 303,701,601,206,602,403,301,502,306,208 -v
    displayName: 'Run Linter on macbook'