trigger:
- main
pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    Python37:
      python.version: '3.7'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  
- script: | 
    ansible-lint  linux/*.yml -x 303,701,601,206,602,403,301,502,306,208 -v
    displayName: 'Run Linter on vps'

- script: | 
    ansible-lint  linux/*.yml -x 303,701,601,206,602,403,301,502,306,208 -v
    displayName: 'Run Linter on linux'

- script: | 
    ansible-lint  linux/*.yml -x 303,701,601,206,602,403,301,502,306,208 -v
    displayName: 'Run Linter on macbook'