trigger:
- main

jobs: 
- job: 'Lint' 
  pool:
    vmImage: 'ubuntu-latest'
  strategy: 
    matrix:
      Python37: 
        python.version: "3.7" 
    maxParallel: 1 
  steps: 

    - script: pip install ansible-lint
      displayName: 'Install All Dependencies needed'
      
  

    - script: ansible-lint install linux/*.yml -x 303,701,601,206,602,403,301,502,306 -v
      displayName: 'Run the Linter on Ubuntu playbooks'
      
    - script: ansible-lint install vps/*.yml -x 303,701,601,206,602,403,301,502,306 -v
      displayName: 'Run the Linter on VPS playbooks'

    - script: ansible-lint install macbook/*.yml -x 303,701,601,206,602,403,301,502,306 -v
      displayName: 'Run the Linter on Macbook Playbooks'