---

- hosts: centos 
  tasks: 
          - name: add repo 
            yum_repository: 
            name: epel 
            description: EPEL YUM REPO 
            baseurl: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
          
          - name: install centos packages 
                    name: "{{ packages }}"
                    state: present
            vars:
                    packages:
                            - vim
                            - unzip
                            - htop
                            - atop
                            - iftop
                            - nmon
                            - sysstat
                            - crash.x86_64
                            - iotop
                            - nicstat
                            - vnstat
                            - vim
                            - htop
                            - nmap
                            - ufw
                            - bridge-utils
                            - lightdm
                            - terminator
                            - cmake
                            - git
                            - libreoffice
                            - net-tools
                            - mailx
                            - postfix
                            - bind-utils
                            - bridge-utils
                            - dnf



          - name: Delete unwanted packages
            yum:
                    name: "{{ packages }}"
                    state: absent
            vars:
                    packages:
                            - nano
                            - firewalld
                            - claws

          - name: install dnf dev tools
            dnf:
                name: "@development tools"



          - name: install multimedia group
            dnf:
                name: "@Multimedia"


          - name: updates all packages
            dnf:
                name: "*"
                state: latest





          - name: create custom directories
            file:
              path: /srv/scripts
              path: /srv/git
              path: /srv/isos
              state: directory



          - name: install terminator, apache, mariadb, pomodoro timer & kvm + it's dependencies
            dnf:
                name:
                  - httpd
                  - mariadb-server
                  - bridge-utils
                  - libvirt
                  - virt-install
                  - qemu-kvm
                  - virt-top
                  - libguestfs-tools
                  - virt-manager
                  - gnome-shell-extension-pomodoro
                  - terminator
                  - lame

