---
- hosts: localhost   
  tasks:
          - name: fedora-vm pacakges  
            yum:
                    name: "{{ packages }}"
                    state: present
            vars:
                    packages:
                            - vim
                            - unzip
                            - htop
                            - atop
                            - iftop
                            - nmon
                            - sysstat
                            - crash.x86_64  
                            - iotop
                            - nicstat
                            - vnstat
                            - vim
                            - htop
                            - nmap
                            - ufw
                            - bridge-utils
                            - libvirt
                            - virt-install
                            - qemu-kvm
                            - lightdm
                            - terminator
                            - cmake
                            - git
                            - thinkfan
                            - libreoffice
                            - net-tools 
                            - mailx 
                            - postfix
                            - bind-utils
                            - bridge-utils
                            - dnf   
          

          - name: checkout git repos 
          - git: 
              repo: "https://github.com/luke-h1/tools" 
              dest: /srv/git/tools  


          - name: checkout config-file repo 
          - git: 
              repo: "https://github.com/luke-h1/configuration-files" 
              dest: /srv/git/configuration-files 


         - name: checkout xfce-themes repo 
         - git: 
              repo: "https://github.com/luke-h1/xfce-themes"   
              dest: /srv/git/xfce-themes 


          - name: 
          - git: 
              repo: "https://github.com/luke-h1/notes" 
              dest: /srv/git/notes 


          - name: create custom directories 
            file: 
              path: /srv/scripts 
              path: /srv/git
              path: /srv/isos 
              path: /srv/wallpapers 
              state: directory

          - name: delete pre-existing xfce4 config directory  
            file: 
              path: /home/lukehowsam/.config/xfce4
              state: absent


          - name: move .vimrc to home directory 
            command: mv /srv/git/configuration-files/.vimrc /home/lukehowsam/ 

          - name: move xfce4 config file to ~/.config 
            command: mv /srv/git/configuration-files/xfce4 /home/lukehowsam/.config/


          - name: move Sly theme to /usr/share/themes 
            command: mv /srv/git/xfce-themes/Sly /usr/share/themes 


          - name: move notes file to home directory 
            command: mv /srv/git/notes /home/lukehowsam  

          - name: remove certain directories 
            file: 
              state: "{{ item }}" 
              path: "/home/lukehowsam/Pictures" 
              path: "/home/lukehowsam/Documents" 
              path: "/home/lukehowsam/Public" 
              path: "/home/lukehowsam/Templates" 
              path: "/home/lukehowsam/Music" 
              path: "/home/lukehowsam/Videos"
            with_items: 
              - absent 
              - directory  
               
          - name: Delete unwanted packages  
            yum:
                    name: "{{ packages }}"
                    state: absent
            vars:
                    packages:
                            - nano
                            - firewalld 
                            - claws

          - name: install dnf dev tools  
            dnf: 
                name: "@development tools" 

          

          - name: install multimedia group 
            dnf: 
                name: "@Multimedia"
          
  
          - name: updates all packages 
            dnf: 
                name: "*"
                state: latest 



             

          - name: install terminator, apache, mariadb, pomodoro timer & kvm + it's dependencies  
            dnf: 
                name:
                  - httpd 
                  - mariadb-server 
                  - bridge-utils
                  - libvirt
                  - virt-install 
                  - qemu-kvm 
                  - virt-top
                  - libguestfs-tools 
                  - virt-manager
                  - gnome-shell-extension-pomodoro
                  - terminator
                  - lame


          - name: install ubuntu 18.04 iso 
            get_url: 
              url: https://releases.ubuntu.com/18.04.4/ubuntu-18.04.4-desktop-amd64.iso 
              dest: /srv/isos/ubuntu-18.04.4-desktop-amd64.iso
  
          - name: install centos 7 minimal iso 
            get_url: 
              url: http://mirrors.ukfast.co.uk/sites/ftp.centos.org/7.7.1908/isos/x86_64/CentOS-7-x86_64-Minimal-1908.iso 
              dest: /srv/isos/CentOS-7-x86_64-Minimal-1908.iso 


          - name:  install Fedora iso 
            get_url:
              url: http://download.fedoraproject.org/pub/fedora/linux/releases/31/Workstation/x86_64/iso/Fedora-Workstation-Live-x86_64-31-1.9.iso
              dest: /srv/isos/Fedora-Workstation-Live-x86_64-31-1.9.iso
 
          
          - name: install arch iso 
            get_url: 
              url: http://mirrors.manchester.m247.com/arch-linux/iso/2020.04.01/archlinux-2020.04.01-x86_64.iso          
              dest: /srv/isos/archlinux-2020.04.01-x86_64.iso 
