--- 
- hosts: localhost 
  become: yes 
  vars: 
    app_name: intel Power Gadget 
    app_url: /content/dam/develop/external/us/en/documents/Intel%20Power%20Gadget.dmg
    installer_type: app 
    install_method: dmg 
    download_file_type: dmg 
  roles: 
    - setup 
    - installer 
    - cleanup 