--- 
- hosts: localhost 
  become: yes 
  vars: 
    app_name: protonVPN 
    app_url: https://protonvpn.com/download/ProtonVPN.dmg
    installer_type: app 
    install_method: dmg 
    download_file_type: dmg 
  roles: 
    - setup 
    - installer 
    - cleanup 