---
- hosts: localhost
  become: yes
  vars:
    app_name: responsivelyApp  
    app_url: https://github.com/manojVivek/responsively-app/releases/download/v0.8.0/ResponsivelyApp-0.8.0.dmg
    installer_type: app
    install_method: dmg
    download_file_type: dmg
  roles:
    - setup
    - installer
    - cleanup
   