---
- hosts: localhost 
  become: yes  
  vars: 
    app_name: firefox
    app_url: https://download.mozilla.org/?product=firefox-devedition-latest-ssl&amp;os=linux64&amp;lang=en-US
    installer_type: app 
    install_method: dmg 
    download_file_type: dmg 
  roles: 
    - setup 
    - installer 
    - cleanup 