---
- hosts: localhost 
  remote_user: lukehowsam 
  tasks: 


          - homebrew_cask:
               name: caffeine 
               state: upgraded


          - homebrew_cask:
               name: iterm2  
               state: upgraded


          - homebrew_cask:
               name: visual-studio-code  
               state: upgraded





          - homebrew_cask:
               name: docker  
               state: upgraded


          - homebrew_cask:
               name: docker-compose  
               state: upgraded


          - homebrew_cask:
               name: docker-machine 
               state: upgraded


          - homebrew_cask:
               name: gpg-suite  
               state: upgraded


          - homebrew_cask:
               name: spectacle  
               state: upgraded

          - homebrew_cask:
               name: insomnia 
               state: upgraded


          - homebrew_cask:
               name: responsively  
               state: upgraded
               

          - homebrew:
               name: wget
               state: latest


          - homebrew:
               name: bash
               state: latest


          - homebrew:
               name: python
               state: latest


          - homebrew:
               name: vcprompt
               state: latest


          - homebrew:
               name: docker-compose
               state: latest


          - homebrew:
               name: docker-machine
               state: latest


          - homebrew:
               name: htop
               state: latest


          - homebrew:
               name: vim
               state: latest



          - homebrew:
               name: openvpn
               state: latest
      


          - homebrew:
               name: tmux
               state: latest
       

          - homebrew:
               name: screen
               state: latest
     


          - homebrew:
               name: dialog
               state: latest
    


          - homebrew:
               name: node
               state: latest



          - homebrew:
               name: nmap
               state: latest
      


          - homebrew:
               name: links
               state: latest
    


              
          - homebrew:
               name: iproute2mac
               state: latest
       


          - homebrew:
               name: watch
               state: latest
   

          - homebrew:
               name: coreutils
               state: latest
  


          - homebrew:
               name: openssl
               state: latest
      


          - homebrew:
               name: pkg-config
               state: latest
      

          - homebrew:
               name: cmake
               state: latest
 


          - homebrew:
               name: readline
               state: latest
 


          - homebrew:
               name: heroku
               state: latest
   


          - homebrew:
               name: tree
               state: latest
  


          - homebrew:
               name: gcc
               state: latest
 


          - homebrew:
               name: gnupg
               state: latest
   


          - homebrew:
               name: p7zip
               state: latest
    


          - homebrew:
               name: ack
               state: latest
         

          - homebrew:
               name: gnutls
               state: latest
        

          - homebrew:
               name: certbot
               state: latest
        


          - homebrew:
               name: mtr
               state: latest
      


          - homebrew:
               name: gnu-sed
               state: latest
 


          - homebrew:
               name: cowsay
               state: latest
   


          - homebrew:
               name: findutils
               state: latest
    


          - homebrew:
               name: gnu-tar
               state: latest



          - homebrew:
               name: aircrack-ng
               state: latest


          - homebrew:
               name: mcrypt
               state: latest


          - homebrew:
               name: libusb
               state: latest



          - homebrew:
               name: fortune
               state: latest
      


          - homebrew:
               name: openssh
               state: latest


          - homebrew:
               name: md5sha1sum
               state: latest



          - homebrew:
               name: pstree
               state: latest
   


          - homebrew:
               name: grep
               state: latest



          - homebrew:
               name: brew-cask-completion 
               state: latest


              
          - homebrew:
               name: moreutils 
               state: latest


          - homebrew:
               name: screenfetch
               state: latest
   


          - homebrew:
               name: docker-completion
               state: latest



          - homebrew:
               name: gpg-agent
               state: latest



          - homebrew:
               name: dockutil
               state: latest
  


          - homebrew:
               name: trash
               state: latest



          - homebrew:
               name: findutils
               state: latest



          - homebrew:
               name: lolcat
               state: latest



          - homebrew:
               name: e2fsprogs
               state: latest



          - homebrew:
               name: webpack
               state: latest



          - homebrew:
               name: gnu-which
               state: latest
     


          - homebrew:
               name: bash-completion
               state: latest



          - homebrew:
               name: bash-git-prompt
               state: latest



          - homebrew:
               name: yarn
               state: latest
               update_homebrew: yes 


          - name: Create srv directory 
            file:
               path: /Users/lukehowsam/srv
               state: directory
               mode: '0755'


          - name: Create iso directory 
            file:
               path: /Users/lukehowsam/srv/isos
               state: directory
               mode: '0755'


          - name: Create /srv/dev directory 
            file:
               path: /Users/lukehowsam/srv/dev
               state: directory
               mode: '0755'


          - name: Create /srv/courses directory 
            file:
               path: Users/lukehowsam/srv/courses
               state: directory
               mode: '0755'

          - name: Create notes directory 
            file:
               path: Users/lukehowsam/notes 
               state: directory
               mode: '0755'


          - name: Install "react" node.js package globally.
            npm:
              name: react
              global: yes 
       

          - name: Install "prop-types" node.js package globally.
            npm:
              name: prop-types
              global: yes 
        

          - name: Install "moment" node.js package globally.
            npm:
              name: moment
              global: yes 
        

          - name: Install "express" node.js package globally.
            npm:
              name: express
              global: yes 
  

          - name: Install "request" node.js package globally.
            npm:
              name: request
              global: yes 
   

          - name: Install "lodash" node.js package globally.
            npm:
              name: lodash
              global: yes 
       

          - name: Install "next" node.js package globally.
            npm:
              name: next
              global: yes 
      


          - name: Install "eslint" node.js package globally.
            npm:
              name: eslint
              global: yes 
      

          - name: Install "async" node.js package globally.
            npm:
              name: async
              global: yes 


          - name: Install "vue" node.js package globally.
            npm:
              name: vue
              global: yes 


          - name: Install "chalk" node.js package globally.
            npm:
              name: chalk
              global: yes 

          - name: Install "debug" node.js package globally.
            npm:
              name: debug
              global: yes 
     


          - name: Install "lite-server" node.js package globally.
            npm:
              name: lite-server
              global: yes 

      
          
