---
- hosts: localhost
  remote_user: lukehowsam
  tasks:
    - shell: ps -eo pcpu,user,args | sort -r -k1 | head -n5     # Print the shell task's stdout.
      register: ps
    - debug: msg={{ ps.stdout }}     # Print all contents of the shell task's output.
    - debug: var=ps

    - homebrew_tap:
        name: mongodb/brew

    - homebrew_tap: 
        name: heroku/brew 

    - homebrew: 
        name: heroku 
        state: latest 

    - homebrew:
        name: mongodb-community@4.2
        state: latest

    - homebrew: 
        name: youtube-dl 
        state: latest 

    - homebrew_cask:
        name: caffeine
        state: latest

    -homebrew_cask: 
        name: spotify 
        state: latest 
        
    - homebrew_cask: 
        name: postman 
        state: latest

    - homebrew_cask:
        name: iterm2
        state: latest

    - homebrew_cask:
        name: visual-studio-code
        state: latest


    - homebrew_cask:
        name: docker
        state: latest

    - homebrew_cask:
        name: vlc
        state: latest

    - homebrew_cask:
        name: spectacle
        state: latest


    - homebrew_cask:
        name: responsively
        state: latest

    - homebrew:
        name: wget
        state: latest

    - homebrew:
        name: bash
        state: latest

    - homebrew:
        name: python
        state: latest

    - homebrew:
        name: vcprompt
        state: latest

    - homebrew:
        name: htop
        state: latest

    - homebrew:
        name: vim
        state: latest

    - homebrew:
        name: openvpn
        state: latest

    - homebrew:
        name: tmux
        state: latest

    - homebrew:
        name: screen
        state: latest

    - homebrew:
        name: dialog
        state: latest

    - homebrew:
        name: node
        state: latest

    - homebrew:
        name: nmap
        state: latest

    - homebrew:
        name: zsh
        state: latest

    - homebrew:
        name: zsh-completions
        state: latest

    - homebrew:
        name: zsh-syntax-highlighting
        state: latest

    - homebrew:
        name: zsh-git-prompt
        state: latest

    - homebrew:
        name: links
        state: latest

    - homebrew:
        name: iproute2mac
        state: latest

    - homebrew:
        name: watch
        state: latest

    - homebrew:
        name: coreutils
        state: latest

    - homebrew:
        name: openssl
        state: latest

    - homebrew:
        name: pkg-config
        state: latest

    - homebrew:
        name: cmake
        state: latest

    - homebrew:
        name: readline
        state: latest

    - homebrew:
        name: tree
        state: latest

    - homebrew:
        name: ack
        state: latest

    - homebrew:
        name: gnutls
        state: latest

    - homebrew:
        name: certbot
        state: latest


    - homebrew:
        name: gnu-sed
        state: latest

    - homebrew:
        name: findutils
        state: latest

    - homebrew:
        name: gnu-tar
        state: latest

    - homebrew:
        name: mcrypt
        state: latest


    - homebrew:
        name: openssh
        state: latest

    - homebrew:
        name: pstree
        state: latest

    - homebrew:
        name: grep
        state: latest

    - homebrew:
        name: brew-cask-completion
        state: latest

    - homebrew:
        name: moreutils
        state: latest

    - homebrew:
        name: screenfetch
        state: latest

    - homebrew:
        name: docker-completion
        state: latest

    - homebrew:
        name: dockutil
        state: latest

    - homebrew:
        name: trash
        state: latest
    
    - homebrew:
        name: findutils
        state: latest


    - homebrew:
        name: e2fsprogs
        state: latest

    - homebrew:
        name: gnu-which
        state: latest

    - homebrew:
        name: bash-completion
        state: latest

    - homebrew:
        name: bash-git-prompt
        state: latest

    - homebrew:
        name: yarn
        state: latest 
    
    - name: start MongoDB pkg 
      command: /usr/local/bin/brew services start mongodb-community@4.2
    
    - name: start openvpn pkg 
      command: /usr/local/bin/brew services start openvpn 
      

    - name: Install OH-MY-ZSH 
      shell: curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh) | sh 
      args:
        creates: ~/.oh-my-zsh/
    

    - homebrew: 
        update_homebrew: yes 
        upgrade_all: yes 

    - name: Create srv directory
      file:
        path: /Users/lukehowsam/srv
        state: directory
        mode: "0755"

    - name: Create iso directory
      file:
        path: /Users/lukehowsam/srv/isos
        state: directory
        mode: "0755"

    - name: Create /srv/dev directory
      file:
        path: /Users/lukehowsam/srv/dev
        state: directory
        mode: "0755"

    - name: Create /Desktop/courses directory
      file:
        path: Users/lukehowsam/Desktop/courses
        state: directory
        mode: "0755"

    - name: Create notes directory
      file:
        path: Users/lukehowsam/notes
        state: directory
        mode: "0755"


    - name: Install "react" node.js package globally.
      npm:
        name: react
        global: yes

 
    - name: Install "moment" node.js package globally.
      npm:
        name: moment
        global: yes

    - name: Install "express" node.js package globally.
      npm:
        name: express
        global: yes

    - name: Install "Mocha" node.js package globally. 
      npm: 
        name: mocha 
        global: yes 


    - name: Install "vercel" node.js package globally.
      npm:
        name: vercel 
        global: yes


    - name: Install "next" node.js package globally.
      npm:
        name: next
        global: yes

    - name: Install "create-react-app" node.js package globally.
      npm:
        name: create-react-app
        global: yes

    - name: Install "eslint" node.js package globally.
      npm:
        name: eslint
        global: yes


    - name: Install "vue" node.js package globally.
      npm:
        name: vue
        global: yes

    
    - name: Install "vue cli" node.js package globally. 
      npm: 
        name: @vue/cli 
        global: yes 


    - name: Install "vue devtools" node.js package globally. 
      npm: 
        name: vue-devtools 
        global: yes 


    - name: Install "lite-server" node.js package globally.
      npm:
        name: lite-server
        global: yes

    - name: Install "nodemon" node.js package globally.
      npm:
        name: nodemon
        global: yes

    - name: Install "artillery" node.js package globally.
      npm:
        name: artillery
        global: yes









        