---
- hosts: localhost
  remote_user: lukehowsam
  tasks:
    - homebrew_tap:
        name: mongodb/brew
      tags:
        - databases

    - homebrew_tap:
        name: heroku/brew
      tags:
        - deployment

    - homebrew:
        name: heroku
      tags:
        - deployment

    - homebrew:
        name: mongodb-community@4.2
      tags:
        - databases
        
    - homebrew:
        name: youtube-dl
      tags:
        - config

    - homebrew_cask:
        name: pycharm
      tags:
        - editors

    - homebrew_cask:
        name: ImageOptim
      tags:
        - Image Optimization
        
    - homebrew_cask:
        name: postman
      tags:
        - Tools

    - homebrew_cask:
        name: iterm2
      tags:
        - Tools

    - homebrew_cask:
        name: visual-studio-code
      tags:
        - Editors

    - homebrew_cask:
        name: vlc
      tags:
        - misc

    - homebrew_cask:
        name: spectacle
      tags:
        - Tools

    - homebrew:
        name: bash
      tags:
        - Tools

    - homebrew:
        name: python
      tags:
        - Tools

    - homebrew:
        name: htop
      tags:
        - Tools

    - homebrew:
        name: vim
      tags:
        - editors

    - homebrew:
        name: openvpn
      tags:
        - Tools

    - homebrew:
        name: tmux
      tags:
        - Tools

    - homebrew:
        name: screen
      tags:
        - Tools

    - homebrew:
        name: node
      tags:
        - Tools

    - homebrew:
        name: nmap
      tags:
        - Tools

    - homebrew:
        name: zsh
      tags:
        - Tools

    - homebrew:
        name: zsh-completions
      tags:
        - Tools

    - homebrew:
        name: zsh-syntax-highlighting
      tags:
        - Tools

    - homebrew:
        name: zsh-git-prompt
      tags:
        - Tools

    - homebrew:
        name: iproute2mac
      tags:
        - Tools

    - homebrew:
        name: watch
      tags:
        - Tools

    - homebrew:
        name: coreutils
      tags:
        - Tools

    - homebrew:
        name: openssl
      tags:
        - Tools

    - homebrew:
        name: pkg-config
      tags:
        - Tools

    - homebrew:
        name: cmake
      tags:
        - Tools

    - homebrew:
        name: readline
      tags:
        - Tools

    - homebrew:
        name: tree
      tags:
        - Tools

    - homebrew:
        name: ack
      tags:
        - Tools

    - homebrew:
        name: gnutls
      tags:
        - Tools

    - homebrew:
        name: certbot
      tags:
        - Tools

    - homebrew:
        name: gnu-sed
      tags:
        - Tools

    - homebrew:
        name: findutils
      tags:
        - Tools

    - homebrew:
        name: gnu-tar
      tags:
        - Tools

    - homebrew:
        name: openssh
      tags:
        - Tools

    - homebrew:
        name: pstree
      tags:
        - Tools

    - homebrew:
        name: grep
      tags:
        - Tools

    - homebrew:
        name: brew-cask-completion
      tags:
        - Tools

    - homebrew:
        name: moreutils
      tags:
        - Tools

    - homebrew: 
        name: watchman
      tags:
        - Tools

    - homebrew:
        name: docker-completion
      tags:
        - Tools

    - homebrew:
        name: findutils
      tags:
        - Tools

    - homebrew:
        name: gnu-which
      tags:
        - Tools

    - homebrew:
        name: bash-completion
      tags:
        - Tools

    - homebrew:
        name: bash-git-prompt
      tags:
        - Tools

    - homebrew:
        name: yarn
      tags:
        - Tools

    - name: Create srv directory
      file:
        path: /Users/lukehowsam/srv
        state: directory
        mode: '0755'
      tags:
        - config

    - name: Create design directory
      file:
        path: /Users/lukehowsam/srv/design
        state: directory
        mode: '0755'
      tags:
        - config

    - name: Create /srv/dev directory
      file:
        path: /Users/lukehowsam/srv/dev
        state: directory
        mode: '0755'
      tags:
        - config

    - name: Create /Desktop/courses directory
      file:
        path: Users/lukehowsam/Desktop/courses
        state: directory
        mode: '0755'
      tags:
        - config

    - name: Create notes directory
      file:
        path: Users/lukehowsam/notes
        state: directory
        mode: '0755'
      tags:
        - config

    - name: Install "react" node.js package globally.
      npm:
        name: react
        global: yes
      tags:
        - npm

    - name: Install "express" node.js package globally.
      npm:
        name: express
        global: yes
      tags:
        - npm

    - name: Install "vercel" node.js package globally.
      npm:
        name: vercel
        global: yes
      tags:
        - npm

    - name: Install "eslint" node.js package globally.
      npm:
        name: eslint
        global: yes
      tags:
        - npm

    - name: Install "lite-server" node.js package globally.
      npm:
        name: lite-server
        global: yes
      tags:
        - npm

    - name: Install "nodemon" node.js package globally.
      npm:
        name: nodemon
        global: yes
      tags:
        - npm

    - name: Install "artillery" node.js package globally.
      npm:
        name: artillery
        global: yes
      tags:
        - npm

    - name: Install "netlify-cli" node.js package globally 
      npm: 
        name: netlify-cli 
        global: yes 
      tags: 
        - Deployment 

    
    - name: Install "gatsby" node.js package globally 
      npm: 
        name: gatsby 
        global: yes 
      tags: 
        - npm 

    - name: Install "pa11y" node.js package globally 
      npm: 
        name: pa11y 
        global: yes 
      tags: 
        - npm 