---
- hosts: localhost
  remote_user: lukehowsam
  tasks:
    - tasks 
    - homebrew_tap:
        name: mongodb/brew

    - homebrew_tap:
        name: heroku/brew

    - homebrew:
        name: heroku

    - homebrew:
        name: mongodb-community@4.2

    - homebrew:
        name: youtube-dl

    - homebrew_cask:
        name: caffeine

    - homebrew_cask:
        name: spotify

    - homebrew_cask:
        name: postman

    - homebrew_cask:
        name: iterm2

    - homebrew_cask:
        name: visual-studio-code

    - homebrew_cask:
        name: docker

    - homebrew_cask:
        name: vlc

    - homebrew_cask:
        name: spectacle

    - homebrew_cask:
        name: responsively

    - homebrew:
        name: wget

    - homebrew:
        name: bash

    - homebrew:
        name: python

    - homebrew:
        name: vcprompt

    - homebrew:
        name: htop

    - homebrew:
        name: vim

    - homebrew:
        name: openvpn

    - homebrew:
        name: tmux

    - homebrew:
        name: screen

    - homebrew:
        name: dialog

    - homebrew:
        name: node

    - homebrew:
        name: nmap

    - homebrew:
        name: zsh

    - homebrew:
        name: zsh-completions

    - homebrew:
        name: zsh-syntax-highlighting

    - homebrew:
        name: zsh-git-prompt

    - homebrew:
        name: links

    - homebrew:
        name: iproute2mac

    - homebrew:
        name: watch

    - homebrew:
        name: coreutils

    - homebrew:
        name: openssl

    - homebrew:
        name: pkg-config

    - homebrew:
        name: cmake

    - homebrew:
        name: readline

    - homebrew:
        name: tree

    - homebrew:
        name: ack

    - homebrew:
        name: gnutls

    - homebrew:
        name: certbot

    - homebrew:
        name: gnu-sed

    - homebrew:
        name: findutils

    - homebrew:
        name: gnu-tar

    - homebrew:
        name: mcrypt

    - homebrew:
        name: openssh

    - homebrew:
        name: pstree

    - homebrew:
        name: grep

    - homebrew:
        name: brew-cask-completion

    - homebrew:
        name: moreutils

    - homebrew:
        name: screenfetch

    - homebrew:
        name: docker-completion

    - homebrew:
        name: dockutil

    - homebrew:
        name: trash

    - homebrew:
        name: findutils

    - homebrew:
        name: e2fsprogs

    - homebrew:
        name: gnu-which

    - homebrew:
        name: bash-completion

    - homebrew:
        name: bash-git-prompt

    - homebrew:
        name: yarn

    - name: start MongoDB pkg
      command: /usr/local/bin/brew services start mongodb

    - name: start openvpn pkg
      command: /usr/local/bin/brew services start openvpn

    - name: Install OH-MY-ZSH
      shell: curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh) | sh
      args:
        creates: ~/.oh-my-zsh/

    - homebrew:
        name: update-homebrew
        update_homebrew: yes
        upgrade_all: yes

    - name: Create srv directory
      file:
        path: /Users/lukehowsam/srv
        state: directory
        mode: '0755'

    - name: Create iso directory
      file:
        path: /Users/lukehowsam/srv/isos
        state: directory
        mode: '0755'

    - name: Create /srv/dev directory
      file:
        path: /Users/lukehowsam/srv/dev
        state: directory
        mode: '0755'

    - name: Create /Desktop/courses directory
      file:
        path: Users/lukehowsam/Desktop/courses
        state: directory
        mode: '0755'

    - name: Create notes directory
      file:
        path: Users/lukehowsam/notes
        state: directory
        mode: '0755'

    - name: Install "react" node.js package globally.
      npm:
        name: react
        global: yes

    - name: Install "moment" node.js package globally.
      npm:
        name: moment
        global: yes

    - name: Install "express" node.js package globally.
      npm:
        name: express
        global: yes

    - name: Install "Mocha" node.js package globally.
      npm:
        name: mocha
        global: yes

    - name: Install "vercel" node.js package globally.
      npm:
        name: vercel
        global: yes

    - name: Install "next" node.js package globally.
      npm:
        name: next
        global: yes

    - name: Install "create-react-app" node.js package globally.
      npm:
        name: create-react-app
        global: yes

    - name: Install "eslint" node.js package globally.
      npm:
        name: eslint
        global: yes

    - name: Install "vue" node.js package globally.
      npm:
        name: vue
        global: yes

    - name: Install "vue devtools" node.js package globally.
      npm:
        name: vue-devtools
        global: yes

    - name: Install "lite-server" node.js package globally.
      npm:
        name: lite-server
        global: yes

    - name: Install "nodemon" node.js package globally.
      npm:
        name: nodemon
        global: yes

    - name: Install "artillery" node.js package globally.
      npm:
        name: artillery
        global: yes
