---
- hosts: localhost   
  tasks:  
          - name:  pacakges  
            yum:
                    name: "{{ packages }}"
                    state: present
            vars:
                    packages:
                            - atop
                            - iftop
                            - htop
                            - nmap
                            - ufw
                            - bridge-utils
                            - libvirt
                            - virt-install
                            - qemu-kvm
                            - cmake
                            - libreoffice
                            - net-tools 
                            - postfix
                            - bind-utils
                            - bridge-utils
                            - dnf
                            - ffmpeg-libs 
                            - vlc
                            - nano 
                            - vim-enhanced.x86_64
                            - mariadb-server
                            - kernel-devel
                            - kernel-headers 
                            - gcc 

           
          - name: install groups 
            yum: 
             name: 
               - "@Virtualization Hypervisor" 
               - "@Virtualization Client" 
               - "@Security Tools" 
               - "@Compatibility Libraries"
               - "@Development Tools"     
          
                    
          - name: updates all packages 
            dnf: 
                name: "*"
                state: latest 


