---
- hosts: localhost   
  remote_user: root 
  tasks: 
          - name: ubuntu packages 
            apt:   
                  name: "{{ packages }}"
                  state: present 
            vars: 
                packages: 
                          - unzip 
                          - htop 
                          - atop 
                          - iftop 
                          - sysstat
                          - iotop
                          - nicstat
                          - vnstat
                          - vim
                          - htop
                          - nmap
                          - ufw
                          - bridge-utils
                          - qemu-kvm
                          - cmake
                          - git
                          - nginx 
                          - mariadb-server
                          - postfix 
                          - net-tools
                          - bridge-utils   
                         
                          
          - name: update all packages 
            apt: 
              name: "*" 
              state: latest  
