---
- hosts: localhost   
  remote_user: lukehowsam 
  tasks: 
          - name: ubuntu packages 
            apt:   
                  name: "{{ packages }}"
                  state: present 
            vars: 
                packages: 
                          - unzip 
                          - htop 
                          - atop 
                          - iftop 
                          - sysstat
                          - iotop
                          - nicstat
                          - vnstat
                          - vim
                          - htop
                          - nmap
                          - ufw
                          - bridge-utils
                          - qemu-kvm
                          - virt-manager 
                          - terminator
                          - cmake
                          - git
                          - libreoffice
                          - nginx 
                          - mariadb-server
                          - postfix 
                          - net-tools
                          - bridge-utils   
                          - transmission-gtk 
                          - caffeine 
                          
