---

- hosts: localhost 
  tasks: 
         - name: install packages 
           yum: 
                 name: "{{packages}}"
                 state: present 
           vars: 
                 packages:
                          - atop
                          - htop 
                          - nmap 
                          - ufw 
                          - libvirt 
                          - virt-install 
                          - qemu-kvm 
                          - cmake 
                          - git 
                          - net-tools 
                          - postfix 
                          - bind-utils 
                          - bridge-utils 
                          - dnf 
                          - nano 
                          - vim-enhanced.x86_64
                          - mariadb-server
                          - xorg-x11-server-source.noarch
                          - pixman 
                          - pixman-devel
                          - libXfont 
                          - tigervnc-server.x86_64
                          - sendmail 
                          - python36 
                          - python36-devel  
         
         
         - name: create custom directories 
           file: 
              path: /srv/scripts 
              path: /srv/git 
              state: directory 

        

         - name: install groups 
           yum:
             name: 
               - "@Virtualization Hypervisor" 
               - "@virtualization Client"
               - "@Security Tools"
               - "@Compatibility Libraries"
               - "@Xfce"
               - "@Development Tools"
               - "@Fonts"




         - name: updates all packages dnf 
           dnf:
               name: "*"
               state: latest 



         - name: updates all packages yum 
           yum: 
            name: "*"
            state: latest 

