---
- hosts: localhost
  remote_user: lukehowsam
  tasks:
    - name: Install "unzip" pkg
      apt:
        name: unzip
        state: present
      tags:
        - config

    - name: Install "htop" pkg
      apt:
        name: htop
        state: present
      tags:
        - config

    - name: Install "zsh" pkg
      apt:
        name: zsh
        state: present
      tags:
        - config

    - name: Install "atop" pkg
      apt:
        name: atop
        state: present
      tags:
        - config

    - name: Install "iftop" pkg
      apt:
        name: iftop
        state: present
      tags:
        - config

    - name: Install "sysstat" pkg
      apt:
        name: sysstat
        state: present
      tags:
        - config

    - name: Install "iotop" pkg
      apt:
        name: iotop
        state: present
      tags:
        - config

    - name: Install "vim" pkg
      apt:
        name: vim
        state: present
      tags:
        - config

    - name: Install "nmap" pkg
      apt:
        name: nmap
        state: present
      tags:
        - config

    - name: Install "ufw" pkg
      apt:
        name: ufw
        state: present
      tags:
        - config

    - name: Install "bridge-utils" pkg
      apt:
        name: bridge-utils
        state: present
      tags:
        - config

    - name: Install "qemu-kvm" pkg
      apt:
        name: qemu-kvm
        state: present
      tags:
        - config

    - name: Install "cmake" pkg
      apt:
        name: cmake
        state: present
      tags:
        - config

    - name: Install "libreoffice" pkg
      apt:
        name: libreoffice
        state: present
      tags:
        - config

    - name: Install "build-essential" pkg
      apt:
        name: unzip
        state: present
      tags: 
        - config 

    - name: Install "openvpn" pkg
      apt:
        name: openvpn
        state: present
      tags:
        - config

    - name: Install "dialog" pkg
      apt:
        name: dialog
        state: present
      tags:
        - config

    - name: Install "python3-pip" pkg
      apt:
        name: python3-pip
        state: present
      tags:
        - config

    - name: Install "python3-setuptools" pkg
      apt:
        name: python3-setuptools
        state: present
      tags:
        - config

    - name: Install "lm-sensors" pkg
      apt:
        name: lm-sensors
        state: present
      tags:
        - config

    - name: Install "virt-manager" pkg
      apt:
        name: virt-manager
        state: present
      tags:
        - config

    - name: Install "pulseaudio" pkg
      apt:
        name: pulseaudio
        state: present
      tags:
        - config

    - name: Install "pavucontrol" pkg
      apt:
        name: pavucontrol
        state: present
      tags:
        - config

    - name: Install "curl" pkg
      apt:
        name: curl
        state: present
      tags:
        - config

    - name: Install "at" pkg
      apt:
        name: at
        state: present
      tags:
        - config

    - name: Install "bluez" pkg
      apt:
        name: bluez
        state: present
      tags:
        - config

    - name: Install "xfce" pkg
      apt:
        name: xfce
        state: present
      tags:
        - config

    - name: Install "terminator" pkg
      apt:
        name: terminator
        state: present
      tags:
        - config

    - name: Install "blueman" pkg
      apt:
        name: blueman
        state: present
      tags:
        - config

    - name: Install "pulseaudio-module-bluetooth" pkg
      apt:
        name: pulseaudio-module-bluetooth
        state: present
      tags:
        - config

    - name: Install "ubuntu-desktop" pkg
      apt:
        name: ubuntu-desktop
        state: present
      tags:
        - config

    - name: Install "unity-control-center" pkg
      apt:
        name: unity-control-center
        state: present
      tags:
        - config

    - name: create custom dirs
      file:
        path: /home/lukehowsam/srv
        state: directory
      tags:
        - config

    - name: create custom dirs
      file:
        path: /home/lukehowsam/srv/dev
        state: directory
      tags:
        - config

    - name: create custom dirs
      file:
        path: /home/lukehowsam/Desktop/courses
      tags:
        - config

    - name: apt-get update
      apt:
        update_cache: yes
      tags:
        - config

    - name: apt-get upgrade
      apt:
        upgrade: dist
      tags:
        - config



    - name: install "create-react-app" pkg globally 
      npm: 
        name: create-react-app
        global: yes 
      tags: 
        - npm 

    - name: Install "pa11y" npm pkg globally 
      npm: 
        name: pa11y
        global: yes 
      tags: 
        - npm 

    - name: Install "node-sass" npm pkg globally 
      npm: 
        name: node-sass
        global: yes 
      tags: 
        - npm
    - name: Install "gatsby" npm pkg globally 
      npm: 
        name: gatsby
        global: yes 
      tags: 
        - npm

    - name: Install "netlify-cli" npm pkg globally 
      npm: 
        name: netlify-cli
        global: yes 
      tags: 
        - npm

    - name: Install "sass" npm pkg globally 
      npm: 
        name: sass
        global: yes 
      tags: 
        - npm

    - name: Install "react-bootstrap" npm pkg globally 
      npm: 
        name: react-bootstrap
        global: yes 
      tags: 
        - npm


    - name: Install "artillery" npm pkg globally 
      npm: 
        name: artillery
        global: yes 
      tags: 
        - npm

    - name: Install "nodemon" npm pkg globally 
      npm: 
        name: nodemon
        global: yes 
      tags: 
        - npm


    - name: Install "node-sass" npm pkg globally 
      npm: 
        name: node-sass
        global: yes 
      tags: 
        - npm

    - name: Install "lite-server" npm pkg globally 
      npm: 
        name: Install "lite-server" npm pkg globally 
        global: yes 
      tags: 
        - npm

    - name: Install "vue devtools" npm pkg globally 
      npm: 
        name: vue-devtools
        global: yes 
      tags: 
        - npm

    - name: Install "vue" npm pkg globally 
      npm: 
        name: vue
        global: yes 
      tags: 
        - npm

    - name: Install "node-sass" npm pkg globally 
      npm: 
        name: node-sass
        global: yes 
      tags: 
        - npm

    - name: Install "vercel" npm pkg globally 
      npm: 
        name: vercel
        global: yes 
      tags: 
        - npm

    - name: Install "eslint" npm pkg globally 
      npm: 
        name: eslint
        global: yes 
      tags: 
        - npm

    - name: Install "Mocha" npm pkg globally 
      npm: 
        name: Mocha
        global: yes 
      tags: 
        - npm


    - name: Install "express" npm pkg globally 
      npm: 
        name: express
        global: yes 
      tags: 
        - npm

    - name: Install "react" npm pkg globally 
      npm: 
        name: react
        global: yes 
      tags: 
        - npm
        
