---
- hosts: localhost   
  tasks:  
          - name:  pacakges  
            yum:
                    name: "{{ packages }}"
                    state: present
            vars:
                    packages:
                            - atop
                            - iftop
                            - htop
                            - nmap
                            - ufw
                            - bridge-utils
                            - libvirt
                            - virt-install
                            - qemu-kvm
                            - lightdm
                            - terminator
                            - cmake
                            - git
                            - libreoffice
                            - net-tools 
                            - postfix
                            - bind-utils
                            - bridge-utils
                            - dnf
                            - ffmpeg-libs 
                            - vlc
                            - gstreamer     
                            - nano 
                            - vim-enhanced.x86_64
                            - mariadb-server
                            - kernel-devel
                            - kernel-headers 
                            - gcc 
          









          - name: create custom directories 
            file: 
              path: /srv/scripts 
              path: /srv/git
              path: /srv/isos 
              path: /srv/wallpapers 
              state: directory


          - name: remove certain directories 
            file: 
              path: "/home/$USER/Pictures" 
              path: "/home/$USER/Documents" 
              path: "/home/$USER/Public" 
              path: "/home/$USER/Templates" 
              path: "/home/$USER/Music" 
              path: "/home/$USER/Videos"
              state: absent 

          - name: Delete unwanted packages  
            yum:
                    name: "{{ packages }}"
                    state: absent
            vars:
                    packages:
                            - firewalld 
                            - claws
            tasks:
           
                    
                    
     
  
          - name: updates all packages 
            dnf: 
                name: "*"
                state: latest 



          - name: install groups 
            yum: 
             name: 
               - "@Virtualization Hypervisor" 
               - "@Virtualization Client" 
               - "@Security Tools" 
               - "@Fedora Packager" 
               - "@Compatibility Libraries"
               - "@Xfce" 
               - "@Development Tools"     

 
