---
- hosts: localhost   
  tasks:  
          - name: fedora-vm pacakges  
            yum:
                    name: "{{ packages }}"
                    state: present
            vars:
                    packages:
                            - atop
                            - iftop
                            - htop
                            - nmap
                            - ufw
                            - bridge-utils
                            - libvirt
                            - virt-install
                            - qemu-kvm
                            - lightdm
                            - terminator
                            - cmake
                            - git
                            - libreoffice
                            - net-tools 
                            - postfix
                            - bind-utils
                            - bridge-utils
                            - dnf
                            - ffmpeg-libs 
                            - vlc
                            - gstreamer     
                            - nano 
          


          - name: create custom directories 
            file: 
              path: /srv/scripts 
              path: /srv/git
              path: /srv/isos 
              path: /srv/wallpapers 
              state: directory


          - name: remove certain directories 
            file: 
              path: "/home/$USER/Pictures" 
              path: "/home/$USER/Documents" 
              path: "/home/$USER/Public" 
              path: "/home/$USER/Templates" 
              path: "/home/$USER/Music" 
              path: "/home/$USER/Videos"
              state: absent 

          - name: Delete unwanted packages  
            yum:
                    name: "{{ packages }}"
                    state: absent
            vars:
                    packages:
                            - firewalld 
                            - claws






           
  
          - name: updates all packages 
            dnf: 
                name: "*"
                state: latest 



          - name: install groups 
            yum: 
             name: 
               - "@Virtualization Hypervisor" 
               - "@Virtualization Client" 
               - "@Security Tools" 
               - "@Fedora Packager" 
               - "@Compatibility Libraries"
               - "@Xfce" 
               - "@Development Tools"     

          - name: mariadb  
            dnf: 
                name:
                  - mariadb-server 


          - name: install ubuntu 18.04 iso 
            get_url: 
              url: https://releases.ubuntu.com/18.04.4/ubuntu-18.04.4-desktop-amd64.iso 
              dest: /srv/isos/ubuntu-18.04.4-desktop-amd64.iso
  
          - name: install centos 7 minimal iso 
            get_url: 
              url: http://mirrors.ukfast.co.uk/sites/ftp.centos.org/7.7.1908/isos/x86_64/CentOS-7-x86_64-Minimal-1908.iso 
              dest: /srv/isos/CentOS-7-x86_64-Minimal-1908.iso 

          - name: install arch iso 
            get_url: 
              url: http://mirrors.manchester.m247.com/arch-linux/iso/2020.04.01/archlinux-2020.04.01-x86_64.iso          
              dest: /srv/isos/archlinux-2020.04.01-x86_64.iso 
