--- 

- hosts: localhost 
  tasks: 
      
          - name: install ubuntu 20.04 iso 
            get_url: 
              url: https://releases.ubuntu.com/20.04/ubuntu-20.04-desktop-amd64.iso?_ga=2.227288724.806720311.1588532690-437922759.1588532690
              dest: /srv/isos/ubuntu-20.04-desktop-amd64.iso
  
          - name: install centos 7 minimal iso 
            get_url: 
              url: http://mirrors.ukfast.co.uk/sites/ftp.centos.org/7.7.1908/isos/x86_64/CentOS-7-x86_64-Minimal-1908.iso 
              dest: /srv/isos/CentOS-7-x86_64-Minimal-1908.iso 

          - name: install arch iso 
            get_url: 
              url: http://mirrors.manchester.m247.com/arch-linux/iso/2020.04.01/archlinux-2020.04.01-x86_64.iso          
              dest: /srv/isos/archlinux-2020.04.01-x86_64.iso 

