---
- hosts: localhost   
  remote_user: root
  tasks: 
          - name: ubuntu packages 
            apt:   
                  name: "{{ packages }}"
                  state: present 
            vars: 
                packages: 
                          - unzip 
                          - htop 
                          - atop 
                          - iftop 
                          - sysstat
                          - iotop
                          - nicstat
                          - vnstat
                          - vim
                          - htop
                          - nmap
                          - ufw
                          - bridge-utils
                          - qemu-kvm
                          - terminator
                          - cmake
                          - git
                          - libreoffice
                          - nginx 
                          - mariadb-server
                          - postfix 
                          - net-tools
                          - bridge-utils   
                          - build-essential
                          - xfce 
                          - openvpn 
                          - dialog 
                          - python3-pip 
                          - python3-setuptools
                          - lm-sensors 
                          - thinkfan
                          - virt-manager  
                      
          - pip:
              name: protonvpn-cli            


          - name: create custom directories 
            file: 
              path: /srv/git 
              path: /srv/isos 
              state: directory 


          - name: remove certain directories 
            file: 
              path: "/home/lukehowwsam/Pictures" 
              path: "/home/lukehowwsam/Documents" 
              path: "/home/lukehowwsam/Public" 
              path: "/home/lukehowwsam/Templates" 
              path: "/home/lukehowwsam/Music" 
              path: "/home/lukehowwsam/Videos"
              state: absent 

       
                          
          - name: update all packages 
            apt: 
              name: "*" 
              state: latest  

