name: Ansible Lint

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Lint Ansible Playbook
        uses: ansible/ansible-lint-action@master
        with:
          targets: |
            macbook/mac-catalina.yml 
            vps/vps.yml
            linux/ubuntu.yml
            
          args: "-x 301, 201, 305, 306, 502, 208"
            
            
                  


