name: CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: luke-h1/checkout@v2.3.4

      - name: Install python 
        run: python -m pip install --upgrade pip

      - name: Install ansible-lint
        run: python -m pip install ansible-lint 

      - name: test 
        run: echo "here"

      # - name: lint playbooks
      #   run: | 
      #   ansible-lint macbook/mac-catalina.yml -x 303,701,601,206,602,403,301,502,306,208,201 -v
